### ISSUE TITLE
grunt 1.0.0 support missing

### ISSUE THREAD

**Issue by jupe** [imyelo/grunt-wait-server#8]
grunt is released as v1.0.0 version and seems that this not working with that version anymore :(
Luckily there is PR workaround already here:
https://github.com/imyelo/grunt-wait-server/pull/7

please look at it and merge if it is okay and publish new version.

**Comment by imyelo** [comment]
Hi @jupe ! PR merged and a new version 0.3.0 released, but to be honest, I don't use grunt now. Would you like to have a try? Let me know if you have any questions.
